# Generated by Django 3.2.12 on 2022-03-31 11:20

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='luffy_user',
        ),
    ]
