# Generated by Django 3.2.12 on 2022-03-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '广告表', 'verbose_name_plural': '广告表'},
        ),
    ]
